apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../ghcr
patches:
  - target:
      version: v1
      kind: Namespace
      name: bounded-lab
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: bounded-lab
