apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  applicationsetcontroller.concurrent.reconciliations: "1"
  applicationsetcontroller.enable.scm.providers: "false"
  controller.kubectl.parallelism.limit: "2"
  controller.operation.processors: "2"
  controller.status.processors: "5"
  reposerver.git.lsremote.parallelism.limit: "2"
  reposerver.parallelism.limit: "2"
  server.webhook.parallelism.limit: "2"
