apiVersion: v1
kind: Secret
metadata:
  name: bounded-lab-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: in-cluster
  server: https://kubernetes.default.svc
  namespaces: bounded-lab
  clusterResources: "false"
  config: "{}"
