apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: observability
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: observability
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: observability
automountServiceAccountToken: false
